### ISSUE TITLE
Request version info from device

### ISSUE THREAD

**Issue by Elkropac** [mathieu-mp/intex-spa#1]
This string is sent by android app during pairing

```{"data":"","sid":"1654467840319","type":3}```

SPA responds with
```
{"sid":"1654467840319","data":"{\"ip\":\"192.168.x.x\",\"uid\":\"0K040210272020102000008062\",\"dtype\":\"spa\"}","result":"ok","type":3}
```
We found out here
https://community.home-assistant.io/t/intex-pure-spa-wifi-control/323591/25
that last four numbers in uid are probably device model - my app says i have `Bubble SPA V28062`

Could you please implement this query in your lib?

Thanks

**Comment by mathieu-mp** [comment]
Nice finding ! There might even be more info to retrieve from this spa response.

Did you identify one or many use cases in which the communication with the spa depends on the spa device model ? It would help me to priorize the feature.

I intend to deliver a first release containing essential features only, allowing me to work on a home assistant integration.
So if this is only "nice to have" I could keep if for subsequent releases.

**Comment by Elkropac** [comment]
Hi, i use this command to have "nice" device name in home assistant integration. It's not needed for cotrolling the spa.

In thread on hass forum, some people used telnet to control SPA using commands I captured on my network and it worked for them, so it seems, there is only one version of their protocol now.

**Comment by mathieu-mp** [comment]
Thank you for your answer.
I'll offer a way to name the integration and I'll keep this feature request for subsequent releases.

**Comment by mathieu-mp** [comment]
Hi @Elkropac, what is the commercial name of your Spa ?

Mine is Carbon 4 pax (Intex ref. 28458EX) and I receive this:
{'ip': 'a.b.c.d', 'uid': '0K040210392021030300016637', 'dtype': 'spa'}
So it does not match the commercial name nor the Intex reference

I'd like to create a map of it

**Comment by Elkropac** [comment]
Mine is called `Pure Spa - Bubble Greywood Deluxe AP 4` in CZ. It's last year model.

What does the original app say about your spa? Does the model correspond to the ending numbers in uid?
