### ISSUE TITLE
Identify spa model and/or features from info response

### ISSUE THREAD

**Issue by mathieu-mp** [mathieu-mp/intex-spa#15]
Following #1

Feature request: Identify spa model and/or features from info response

**Comment by mathieu-mp** [comment]
For future reference, below is a table of the user/uid/model/feature gathered from here and the [forum thread](https://community.home-assistant.io/t/intex-pure-spa-wifi-control/323591/) :

| User  | UID | Name on Intex App | User manual Ref. | Intex Spa FR ref. | Intex Spa FR Name |
| :---: | :---: | :---: | :---: | :---: | :---: |
| mathieu-mp  | ? | `0K040210392021030300016637`  | PureSpa SC-WF20  | 28458EX | Carbone 4p |
| Djes  | Bubble SPA2448 | `0K04############2000002448`  | PureSpa Greywood Deluxe 6p SB-HWF20 | 28442EX | Baltik 6p |

**Comment by FredericMa** [comment]
I have the following spa:
UID: 0K040220252021122800018539
Name on Intex App: Bubble SPA Plus8539
User manual Ref.: PureSpa Greywood Deluxe SB-HSWF20
Intex Spa FR ref.: 28452EX
Intex Spa FR Name: Ardoise 6p

It looks like the UID and "Name on Intex App" columns are swapped in your post above.

**Comment by RoyEssers** [comment]
Info from my Spa Model:
UID: 0K040220122021081800011284
Name on Intex App: Bubble SPA V21284
User manual Ref.: PureSpa Greywood Deluxe SB-HWF20
Intex Spa ref.: 28440NL
Intex SpaName: Bubble Massage Greywood Deluxe 4P

**Comment by mathieu-mp** [comment]
Hi @Elkropac, would you tell us what is your spa:
* User manual Reference
* Intex Spa ref.
* [Intex Spa FR](https://www.intex.fr/shop/34-spa-gonflable) Name
Thanks !

**Comment by mathieu-mp** [comment]
Hi @Rolrik, would you please tell us what is your spa:
* UID
* Name on Intex App
* User manual Ref.
* Intex Spa ref.
* Intex Spa FR Name

If you don't have your spa uid, I will provide a way to retrieve it easily.

**Comment by mathieu-mp** [comment]
Hi @Rolrik, 

> Intex Spa ref. : 28442EX Intex Spa FR Name : PureSpa Baltik 6p

Nice : now we have 2 users with the same model. It should help to understand the uid !
I'm so excited !

> I don't have the UUID.

I just updated the home assistant integration. You can now enable a "UID" sensor to display it!

> FYI, i'm from France

No need to heat the spa these days, right ?

**Comment by Elkropac** [comment]
> Hi @Elkropac, would you tell us what is your spa:
> 
> * User manual Reference
> * Intex Spa ref.
> * [Intex Spa FR](https://www.intex.fr/shop/34-spa-gonflable) Name
>   Thanks !

Hi, i don't know , if i still have manual ;)

I have this i think "Spa gonflable Baltik 4 places" , REF. 28440EX , model 2021
Sticker on device is 
![20220713_103724~2](https://user-images.githubusercontent.com/28620417/179857413-cef949f9-54ce-4592-b50d-6acab455f3cb.jpg)

**Comment by Rolrik** [comment]
Just update my Comment. 
And yes no need to heat it up, 35°C yesterday afternoon without heating.

**Comment by Elkropac** [comment]
> Just update my Comment. And yes no need to heat it up, 35°C yesterday afternoon without heating.

Wow, crazy. I'm waiting for my friend to 3d print adapter, so i can connect solar heater to my SPA, water is now 23°C without heating, which is good, we use it to cool ourselves

**Comment by FredericMa** [comment]
28452 is in between; it doesn't have jets but it does has a sanitizer. 😄

**Comment by ntls2000** [comment]
trtrt

**Comment by ntls2000** [comment]
Intex Pure Spa Carbone 4 places - modèle 2022
Bubble / Jets / Sanitizer
ProductName: Combo SPA V21462
UID: 0K040220312021122000001462

**Comment by mathieu-mp** [comment]
**UUID Visual reverse engineering**

Starting from the UUID, I suppose I can read dates, serial numbers, and/or firmware versions:
`0K040 21039 20210303 00016637`
But I cannot find a logic by analyzing et comparing identical/different spa models UUID to clearly identify the model from the UUID. I am mainly blocked by the presence of identical uuid blocs on 2 different models.

So I personally can't make the UUID match the model by uuid visual reverse engeneering.

**Uncompiled Intex App Reverse engineering**

In the uncompiled Intex App, the identification of the spa model/features is made by requesting the cloud server, so I guess Intex keeps a map of uuid to model/feature.
It would be a solution to make an similar request to the spa cloud.

**Impact of non implementation of this feature request**
Not implementing this feature request means the user has to disable the features that his spa does not implement (sanitizer and/or jets).
From a python library point of view, not disabling this features does not lead to any error or exception.
From a user point of view, it looks like everything works while the non-existant jets or sanitizer actually do nothing.

**Conclusion at this time**
At this time, the only identified solution is to request the Intex cloud to gather the spa feature from its uuid.
Considering the low impact of non-implementation, it feels like it is not worth the time to develop it.

**Contribution appreciated**
Any contribution to help understanding how to associate a uuid to its spa model would be appreciated.
If the logic is understood, I can develop the corresponding code.
While the logic is not understood, I will not implement this feature request.

**Comment by Elkropac** [comment]
Hi,
for me , most reasonable way is to use only the last 4 digits of uid to get the features.
Also when fifth digit from back is non-zero, it seems to mean V2.

Make the detection using just one big switch statement on last 4 digits. With all features enabled for unknown model number as fallback.
If some variation of known uid with different features appears, then deal with it afterwards?

Is  there a way to tell home assistant user, that his model is not known and ask him to create feature request on github with his mode/uid ?

**Comment by Elkropac** [comment]
Hi @mathieu-mp ,
you are right, i don't know what i saw there ...

Without more data , there is no way to even try to recognize some pattern in uid

**Comment by rogerveijk** [comment]
UID: 0K040210202020082000001395
Name on Intex App: Bubble SPA0139
User manual Ref. : Greywood deluxe for 6p Ref. 21SB-HWF20**A0
Intex Spa ref. : 28442NL

**Comment by networks514** [comment]
Hi

Intex Pure Spa Chevron 4 places - modèle 2023 

User manual Ref : PureSpa SB-HSWF20
 Name on Intex App : Bubble SPA Plus3380 
UID: 0K040220262022010600013380
bubble / sanitizer

**Comment by montgomeryb** [comment]
Thanks.. Here's another entry:
UID: 0K040210272020102000002924
Name on Intex App: Combo SPA V22924
User manual Ref. : PureSpa SC-WF10
Intex Spa ref. : 28461E
