### ISSUE TITLE
Question: Domoticz plugin

### ISSUE THREAD

**Issue by Fabaude** [mathieu-mp/intex-spa#23]
Hello, (thanks google translation, I'm French without great English skills!), I would like to know if your plugin could be installed on a raspberry with Domoticz? If so, could you show me how to do it? Where to start ? knowing that I am not an expert like you but a simple guy who would like to enjoy his spa via his home automation!
Thank you for your understanding.
Sincerely

ps: I hope not to disturb the project, I did not know how to contact you.

**Comment by mathieu-mp** [comment]
Hi @Fabaude,

This project is released as a Python module, and is licensed in a way that it can be used whatever your home automation distro, as soon as it can run Python.

This Python module provides an interface with the Intex Spa wifi module (with all the odds of the Intex protocol).
You will need to create an adapter on your home automation to be able to use the Python module.
I personally use it [from Home Assistant](https://github.com/mathieu-mp/homeassistant-intex-spa), but you should be able to use it from Domoticz. A quick search reveals that [developing it is well documented on Domoticz documentation/wiki](https://www.domoticz.com/wiki/Developing_a_Python_plugin).

I don't know Domoticz, so I am not the best person to help.
For sure, people on some Domoticz forum will have already talked about automating Intex Spa, so this is where you should look for some help. This Python package might be the starting point of such a development.

Please keep us updated !

**Comment by Fabaude** [comment]
Hello and thank you for your feedback,
I therefore allow myself to make a request on a dedicated Domoticz forum!
 I come back to you if I have news, on this same subject (issues) or elsewhere?
Thanks

**Comment by Fabaude** [comment]
Hello, 
I actually asked my question on Easydomoticz, without answers for the moment!
https://easydomoticz.com/forum/viewtopic.php?f=15&t=12638
And I couldn't register on Domoticz!!!
So... Thank you for your interest.
I will surely look for another solution.  (this is also the period when all the spas are tidied up ;-))
