### ISSUE TITLE
Can I use this also for Raspi and node-red?

### ISSUE THREAD

**Issue by Malvin76** [mathieu-mp/intex-spa#24]
Hi, 
can I use it also for a raspi and node red?
I use the stuff from Claudio, but only the status stuff is working but I need the action commands.
Thanks.

cheers, Peter
```

**Comment by mathieu-mp** [comment]
Hi @Malvin76,

Did you get the chance to go further with this implementation?
About Claudio, what stuff are you referring to?

Cheers, Mathieu.

**Comment by Malvin76** [comment]
No Unfortunately not... I have unfortunately few programming knowledge. He had programmed a Node-Red implementation for the INTEX Spa. The status also works without problems only the active part does not work for me. And I would need this Active function urgently!

**Comment by mathieu-mp** [comment]
Could you point to Claudio's work, for future reference, please ? As a link ?
Node-Red users could be interrested in it, and it could help to go on developing this python package.

**Comment by Malvin76** [comment]
Yeas sure .... here is the link https://github.com/claudiospizzi/node-red-contrib-intexspa
