### ISSUE TITLE
Get battery info

### ISSUE THREAD

**Issue by supermenteur** [mathieu-mp/intex-spa#25]
Hi Mathieu,

Nice job. 
Jeedom integration done and quite easy. 

Will it be possible to get battery info at some point?

Cheers,
Patrice

**Comment by mathieu-mp** [comment]
Hi @supermenteur (Patrice),

I'm so glad you were able to use this code to provide spa access to Jeedom users! That's a very good news for Jeedom community.
Could you provide a link to the Jeedom plugin you created ?

About your question: do you mean retrieving the battery level of the remote control ?
I couldn't find this status value while reverse-engineering the Intex protocol.
Is this information available from the official Intex app ?

Regards, Mathieu.

**Comment by supermenteur** [comment]
it's not a plug-in. I'm not so smart to develop it. it's based on scripts, virtual and scenario.
it does the job. maybe a dev will take it and create a true plug-in.

I can't tell you if the battery info is available or nor. The app is a crap and unusable. So, I'm not using it.

Patrice

________________________________
De : mathieu-mp ***@***.***>
Envoyé : Monday, May 29, 2023 7:12:10 PM
À : mathieu-mp/intex-spa ***@***.***>
Cc : Patrice Payen ***@***.***>; Mention ***@***.***>
Objet : Re: [mathieu-mp/intex-spa] Get battery info (Issue #25)


Hi @supermenteur<https://github.com/supermenteur> (Patrice),

I'm so glad you were able to use this code to provide spa access to Jeedom users! That's a very good news for Jeedom community.
Could you provide a link to the Jeedom plugin you created ?

About your question: do you mean retrieving the battery level of the remote control ?
I couldn't find this status value while reverse-engineering the Intex protocol.
Is this information available from the official Intex app ?

Regards, Mathieu.

**Comment by mathieu-mp** [comment]
OK, I hope it will give some ideas to a dev !

I don't think this info can be retrieved with the spa status, so I can't add the feature you suggested.
If anyone wants to help on this, they're more than welcome!

By now, I am closing this issue.
It can be reopened in the future.

Regards, Mathieu.
